<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Concourse.Application\Concourse.Application.csproj" />
    <ProjectReference Include="..\Concourse.Persistence\Concourse.Persistence.csproj" />
    <ProjectReference Include="..\Concourse.Infrastructure\Concourse.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
